global using System.Text;
global using Application.DTOs;
global using Application.Interfaces;
global using Infrastructure;
global using Mapster;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.OpenApi.Models;
